# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Backupctl < Formula
  desc "CLI tool for setting up restic-based database backups"
  homepage "https://github.com/Solo-it/backupctl"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Solo-it/backupctl/releases/download/v1.0.0/backupctl_1.0.0_darwin_amd64.tar.gz"
      sha256 "fc17e695c6cb872a6110be10830291c1dc331ec34e84a32237a30c09d80cce8d"

      define_method(:install) do
        bin.install "backupctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Solo-it/backupctl/releases/download/v1.0.0/backupctl_1.0.0_darwin_arm64.tar.gz"
      sha256 "ed0fb2cdc805d7bea8d3760513961ee3901d8952b417946e145e15a7687e34c3"

      define_method(:install) do
        bin.install "backupctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Solo-it/backupctl/releases/download/v1.0.0/backupctl_1.0.0_linux_amd64.tar.gz"
      sha256 "4b05aebb16bb23f1b6f66af02aabe594608a72260d1f2a6ba8004150dfbc5400"
      define_method(:install) do
        bin.install "backupctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Solo-it/backupctl/releases/download/v1.0.0/backupctl_1.0.0_linux_arm64.tar.gz"
      sha256 "4dfcbefe67f62103edd1838b05bcf40dbde84308ea5ea132c7d8ceb4d2a0fd1d"
      define_method(:install) do
        bin.install "backupctl"
      end
    end
  end
end
