# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Backupctl < Formula
  desc "CLI tool for setting up restic-based database backups"
  homepage "https://github.com/Solo-it/backupctl"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Solo-it/backupctl/releases/download/v1.0.1/backupctl_1.0.1_darwin_amd64.tar.gz"
      sha256 "adaa8b4b647d0f7f69bea2ac77e77ea712b27200337cb82ed3fa7654d798dd15"

      define_method(:install) do
        bin.install "backupctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Solo-it/backupctl/releases/download/v1.0.1/backupctl_1.0.1_darwin_arm64.tar.gz"
      sha256 "1a21deab207341eb473bcac569cf42d13deeae8b03f4f5fc8ee7f86c3d1ab253"

      define_method(:install) do
        bin.install "backupctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Solo-it/backupctl/releases/download/v1.0.1/backupctl_1.0.1_linux_amd64.tar.gz"
      sha256 "c1604dbde283ca0bc01a8a17da5d92c22eb5f8438c5c904472d9a05510bfcdd6"
      define_method(:install) do
        bin.install "backupctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Solo-it/backupctl/releases/download/v1.0.1/backupctl_1.0.1_linux_arm64.tar.gz"
      sha256 "31bcc0c16f2c96c5fe793bb1815d47c898b0858f30450b60faf638a1600f00aa"
      define_method(:install) do
        bin.install "backupctl"
      end
    end
  end
end
